# -*- coding: utf-8 -*-
"""4_unit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1napdXrzCXDHEepnRq0HE1CN-eIogsJHv
"""

import pandas as pd
examplelist=[1,2,3,4,5,6]
exampleseries=pd.Series(examplelist)
print(exampleseries)

import pandas as pd
examplelist=[1,2,3,4,5,6]
exampleseriestwo=pd.Series(examplelist,index=['A','B','C','D','E','F'])
print(exampleseriestwo)

import pandas as pd
x=pd.Series()
print(x)

import numpy as np
import pandas as pd
series_arrays=np.array(['P','A','N','D','A',123])
print(series_arrays)
sa=pd.Series(series_arrays)
print(sa)

import numpy as np
import pandas as pd
series_dict=np.array({'A':12,'B':23 ,'C':34})
print(series_dict)
sa=pd.Series(series_dict)
print(sa)

import pandas as pd
s=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s.index)
print(s.values)
print(s[0])
print(s[2])
print(s[1:3])
print(s['b':'d'])

import pandas as pd
s=pd.Series([10,20,30],index=['a','b','c'])
print(s.index)
print(s.shape)
print(s.dtype)
print(s.size)
s3=pd.Series([])
print(s3.empty)

import pandas as pd
data={'apples':[3,2,0,1],'oranges':[3,7,5,9]}
df=pd.DataFrame(data,index=['harshini','kalpana','hema','thanusha'])
print(df)
df.loc['hema']

import pandas as pd
data={'col_1':[3,2,0,1],'col_2':['a','b','c','d']}
pd.DataFrame.from_dict(data)

import pandas as pd
data={'row_1':[3,2,0,1],'row_2':['a','b','c','d']}
pd.DataFrame.from_dict(data,orient='index',columns=['col_1','col_2','col_3','col_4'])

#4.11
import pandas as pd
#creating a one dimensional array-like object using series
data=pd.Series([10,20,30,40])
#displaying the series
print("One-dimensional array-like object(pandas Series):")
print(data)

#4.12
import pandas as pd
#create a pandas sries
data=pd.Series([10,20,30,40])

#convert series to python list
data_list=data.tolist()

#display the list and it's type
print("Python List:",data_list)
print("type:",type(data_list))

#4.2(a)
import pandas as pd
import numpy as np

# Sample dictionary data
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
              'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes',
                'yes', 'no', 'no', 'yes']
}

# List of index labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Display DataFrame
print("DataFrame from the given dictionary data:")
print(df)

#4.2(b)
import pandas as pd
import numpy as np

# Sample dictionary data
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
              'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes',
                'yes', 'no', 'no', 'yes']
}

# List of index labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Change name 'James' to 'Suresh'
df.loc[df['name'] == 'James', 'name'] = 'Suresh'

# Display updated DataFrame
print("DataFrame after changing name 'James' to 'Suresh':")
print(df)

#4.2(c)
import pandas as pd
import numpy as np

# Sample dictionary data
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'Suresh', 'Emily',
              'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes',
                'yes', 'no', 'no', 'yes']
}

# List of index labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Insert new column 'age' with values
df['age'] = [18, 20, 19, 21, 20, 22, 19, 18, 20, 21]

# Display updated DataFrame
print("DataFrame after inserting new column 'age':")
print(df)

#4.2(d)
import pandas as pd
import numpy as np

# Sample dictionary data
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'Suresh', 'Emily',
              'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes',
                'yes', 'no', 'no', 'yes']
}

# List of index labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Get list of column headers
column_list = df.columns.tolist()

# Display the list
print("List of column headers:")
print(column_list)

#4.2(e)
import pandas as pd
import numpy as np

# Sample dictionary data
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'Suresh', 'Emily',
              'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes',
                'yes', 'no', 'no', 'yes']
}

# List of index labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Get list of row headers (index labels)
row_labels = df.index.tolist()

# Display the list
print("List of row headers (index labels):")
print(row_labels)