# -*- coding: utf-8 -*-
"""5th_unit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuQzNvQXrw7Sxe8HA0SMB8n5jNRCQ-JO
"""

import matplotlib.pyplot as plt
x=[0,1,2,3,4]
y=[0,1,2,3,4]
plt.plot(x,y)
plt.title("Line Plot Example")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4])
y=np.array([0,1,2,3,4])
plt.scatter(x,y)
plt.title("scatter Plot Example")
plt.xlabel("Car Age")
plt.ylabel("Car Speed")
plt.show()

import matplotlib.pyplot as plt
x=[0,1,2,3,4]
y=[0,1,2,3,4]
plt.plot(x,y,color='red',linestyle='--',marker='s')
plt.grid(True)
plt.title("Customized Line Example")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.show()

import matplotlib.pyplot as plt
x=[0,1,2,3,4]
y=[0,1,2,3,4]
plt.bar(x,y,color='aqua',edgecolor='green')
plt.title("Vertical Bar Example")
plt.xlabel("Category")
plt.ylabel("Value")
plt.show()
x=[0,1,2,3,4]
y=[0,1,2,3,4]
plt.barh(x,y,color='pink',edgecolor='blue')
plt.title("Horizontal Bar Example")
plt.xlabel("Category")
plt.ylabel("Value")
plt.show()

#5.1
import matplotlib.pyplot as plt
x=[0,1,2,3,4]
y=[0,1,2,3,4]
#Line plot(trend)
plt.plot(x,y)
plt.title("Line Plot Example")
plt.show()
#Scatter Plot(relation)
plt.scatter(x,y)
plt.title("scatter Plot Example")
plt.show()
#Bar plot
plt.bar(x,y,color='pink',edgecolor='blue')
plt.title("Bar chart with custom colors")
plt.xlabel("Category")
plt.ylabel("Value")
plt.show()

#5.2) Generate a subplot layout with various plot types(scatter,line,bar).
import numpy as np
import matplotlib.pyplot as plt
#Data
x=np.linspace(0,10,100)
y=np.sin(x)
#Create subplots (2 rows,2 columns)
fig,axs=plt.subplots(2,2,figsize=(8,6))
#Line Plot
axs[0,0].plot(x,y,color='pink')
axs[0,0].set_title("Line Plot")
#Scatter plot
axs[0,1].scatter(x,y,color='green')
axs[0,1].set_title("Scatter Plot")
#Bar plot
axs[1,0].bar(x,y,color='blue')
axs[1,0].set_title("Bar Plot")
#Create Histogram
data=np.random.randn(1000)  #1000 random numbers (normal distribution)
axs[1,1].hist(data,bins=30,color='orange',edgecolor='black')
axs[1,1].set_title('Histogram Example')
#Display the output
plt.show()
#Adjust space
plt.tight_layout()
plt.show()

#5.3
import matplotlib.pyplot as p
import numpy as np
import pandas as pd
import matplotlib.dates as mdates
#simulate time series data
date_rng=pd.date_range(start='2025-12-01',end='2025-12-10',freq='D')
data=np.random.randn(len(date_rng))
fig,axs=p.subplots()
axs.plot(date_rng,data)
#label axis and use custom date format
axs.set_xlabel("Date")
axs.set_ylabel("Measurement")
axs.set_title("Time series visualization")
axs.xaxis.set_major_formatter(mdates.DateFormatter('%d-%b'))
p.xticks(rotation=45)
p.tight_layout()
p.show()

#5.3)Create a 3D plot
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
# Create a 3D figure
fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')
z=np.linspace(0,1,100)
x=z*np.sin(25*z)
y=z*np.cos(25*z)
ax.plot(x,y,z,color='green')
ax.set_title("3D Line Plot")
plt.show()