a=int(input("Enter a value:"))
print(a)
b=input("Enter your name:")
print(b)
a=float(input("Enter a number:"))
print(a)
b=bool(input("Enter a number:"))
print(b)
print(bool(input("Enter a number:")))
